/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Contacts } from "./Contacts";
export * as factories from "./factories";
export { Contacts__factory } from "./factories/Contacts__factory";
